"""Добавлена таблица Tasks

Revision ID: beaea47c96bf
Revises: 
Create Date: 2022-08-22 15:54:36.220567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaea47c96bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор задачи'),
    sa.Column('title', sa.String(), nullable=False, comment='Описание задачи'),
    sa.Column('done', sa.Boolean(), nullable=False, comment='Флаг выполнения задачи'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
